gps_primary:
  ros__parameters:
    # --- Primary GPS ---
    # Serial port settings
    # port: "/dev/ttyACM0"
    port: "/dev/ttyUSB0"
    baud: 9600
    # ROS-specific settings
    frame_id: "gps_primary_link"
    time_ref_source: "gps_primary"
    # NMEA message parsing options
    useRMC: False